from sqlalchemy import Column, Integer, Float, Boolean, ForeignKey
from sqlalchemy.orm import relationship
from app.core.database import Base

class MoldingMachineState(Base):
    __tablename__ = "molding_machine_states"
    
    id = Column(Integer, primary_key=True, index=True)
    inspection_id = Column(Integer, ForeignKey("product_inspections.id"), nullable=False)
    
    VtoPTime = Column(Float, nullable=True)
    InjStartPos = Column(Float, nullable=True)
    HoldSegment5PressureSP = Column(Float, nullable=True)
    VPTransferTimeSP = Column(Float, nullable=True)
    FillSegment3pressureSP = Column(Float, nullable=True)
    FillSegment4SP = Column(Float, nullable=True)
    FillSegmentXfer1to2SP = Column(Float, nullable=True)
    H2TempSP = Column(Float, nullable=True)
    Barrel5 = Column(Float, nullable=True)
    HoldSegment2PressureSP = Column(Float, nullable=True)
    BuzzerAlarm = Column(Boolean, nullable=True)
    H1TempSP = Column(Float, nullable=True)
    EjFwdTimeCV = Column(Float, nullable=True)
    FillSegmentXfer4to5SP = Column(Float, nullable=True)
    FillSegment4pressureSP = Column(Float, nullable=True)
    H6TempSP = Column(Float, nullable=True)
    FillSegment5SP = Column(Float, nullable=True)
    Barrel2 = Column(Float, nullable=True)
    HoldSegment4TimeSP = Column(Float, nullable=True)
    PullBackBeforeSP = Column(Float, nullable=True)
    H3TempSP = Column(Float, nullable=True)
    Barrel6 = Column(Float, nullable=True)
    HoldSegment1PressureSP = Column(Float, nullable=True)
    FillSegment2pressureSP = Column(Float, nullable=True)
    AlarmLED = Column(Boolean, nullable=True)
    ShotCount = Column(Integer, nullable=True)
    FillSegment1SP = Column(Float, nullable=True)
    CushionMin = Column(Float, nullable=True)
    ClampOpenTimeCV = Column(Float, nullable=True)
    ClampCloseTimeCV = Column(Float, nullable=True)
    InjTimeSP = Column(Float, nullable=True)
    HoldSegment3PressureSP = Column(Float, nullable=True)
    FillSegment3SP = Column(Float, nullable=True)
    CycleTime = Column(Float, nullable=True)
    N1TempSP = Column(Float, nullable=True)
    HoldSegment4PressureSP = Column(Float, nullable=True)
    ClampForceSP = Column(Integer, nullable=True)
    Barrel4 = Column(Float, nullable=True)
    FillSegment5pressureSP = Column(Float, nullable=True)
    N2TempSP = Column(Float, nullable=True)
    VtoPPos = Column(Float, nullable=True)
    Barrel1 = Column(Float, nullable=True)
    VtoPPress = Column(Float, nullable=True)
    H4TempSP = Column(Float, nullable=True)
    FillSegment2SP = Column(Float, nullable=True)
    HoldSegment1TimeSP = Column(Float, nullable=True)
    PullBackAfterSP = Column(Float, nullable=True)
    InjPeakPressure = Column(Float, nullable=True)
    FillSegmentXfer3to4SP = Column(Float, nullable=True)
    ChargeTime = Column(Float, nullable=True)
    FillSegmentXfer2to3SP = Column(Float, nullable=True)
    BarrelN2 = Column(Float, nullable=True)
    TonnageForceCV = Column(Integer, nullable=True)
    CoolTimeSP = Column(Float, nullable=True)
    FillSegment1pressureSP = Column(Float, nullable=True)
    H5TempSP = Column(Float, nullable=True)
    FillPeakPress = Column(Float, nullable=True)
    ShotSizeSP = Column(Float, nullable=True)
    HoldSegment3TimeSP = Column(Float, nullable=True)
    BarrelN1 = Column(Float, nullable=True)
    CushionFin = Column(Float, nullable=True)
    Barrel3 = Column(Float, nullable=True)
    EjRetTimeCV = Column(Float, nullable=True)
    CycleStopFault = Column(Boolean, nullable=True)
    HoldSegment2TimeSP = Column(Float, nullable=True)
    VPTransferPositionSP = Column(Float, nullable=True)
    
    inspection = relationship("ProductInspection", back_populates="molding_machine_state")